version: '3.9'

services:
  db:
    image: postgres
    container_name: ${DB_SERVICE_NAME} 
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
     - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/data

  python:
    image: python:3.9-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PYTHON_CONTAINER}
    restart: always
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./requirements.txt:/requirements.txt
      - ./credentials.env:/credentials.env
    working_dir: /scripts
    command: ["sh", "-c", "pip install -r /requirements.txt && tail -f /dev/null"]
