## 
## ----------------------------------------------------------------------
## Welcome to the 3th delivery of the final project. Coderhouse's Data Engineering
## Student: Orengia Christian
## Commission: 61890
## ----------------------------------------------------------------------
## With this delivery you will
## - extract data from Population.io and Open-Meteo
## - transform it to be used in the study of the relation between the
## wheather and the population movements around the world
## - Load it to a data warehouse in redshift
## - To do this, Airflow will be used with a DAG that runs every day retrieving 1 year
## of information from the APIs. Always starting by the max year on the database.
## ----------------------------------------------------------------------
## 
## Available command list:
## 

build: ## build the solution
	docker compose down --volumes --remove-orphans
	docker compose up