version: '3.9'

services:
  db:
    image: postgres
    container_name: ${PG_SERVICE_NAME} 
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${PG_PWD}
    ports:
     - ${PG_PORT}:${PG_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/data
      - ./sql-etl-process:/sql-etl-process

  python:
    image: python:3.9-slim
    container_name: python-etl
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./requirements.txt:/requirements.txt
    working_dir: /scripts
    depends_on:
      - db
    command: ["sh", "-c", "pip install -r /requirements.txt && tail -f /dev/null"]
