version: '3.9'

services:
  db:
    image: postgres
    container_name: redshift-instance 
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: dataEngineering
    ports:
     - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/data
      - ./sql-etl-process:/sql-etl-process

  python:
    image: python:3.9-slim
    container_name: python-etl
    restart: always
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    depends_on:
      - db
    command: ["tail", "-f", "/dev/null"]
